[2025-02-13T06:19:25.268+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: download_dataset.transform_dataset manual__2025-02-13T06:14:05.847375+00:00 [queued]>
[2025-02-13T06:19:25.278+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: download_dataset.transform_dataset manual__2025-02-13T06:14:05.847375+00:00 [queued]>
[2025-02-13T06:19:25.278+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-13T06:19:25.288+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonVirtualenvOperator): transform_dataset> on 2025-02-13 06:14:05.847375+00:00
[2025-02-13T06:19:25.295+0000] {standard_task_runner.py:57} INFO - Started process 815 to run task
[2025-02-13T06:19:25.299+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'download_dataset', 'transform_dataset', 'manual__2025-02-13T06:14:05.847375+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/download_dataset_dag.py', '--cfg-path', '/tmp/tmpgz54xmzu']
[2025-02-13T06:19:25.303+0000] {standard_task_runner.py:85} INFO - Job 28: Subtask transform_dataset
[2025-02-13T06:19:25.350+0000] {task_command.py:416} INFO - Running <TaskInstance: download_dataset.transform_dataset manual__2025-02-13T06:14:05.847375+00:00 [running]> on host 081769f0e6bd
[2025-02-13T06:19:25.647+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='download_dataset' AIRFLOW_CTX_TASK_ID='transform_dataset' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T06:14:05.847375+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T06:14:05.847375+00:00'
[2025-02-13T06:19:25.649+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvnflg40q7
[2025-02-13T06:19:25.661+0000] {process_utils.py:186} INFO - Output:
[2025-02-13T06:19:26.777+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 254ms
[2025-02-13T06:19:26.778+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvnflg40q7, clear=False, no_vcs_ignore=False, global=False)
[2025-02-13T06:19:26.778+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2025-02-13T06:19:26.779+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.2.1, setuptools==68.2.0, wheel==0.41.2
[2025-02-13T06:19:26.779+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2025-02-13T06:19:26.819+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvnflg40q7/bin/pip install -r /tmp/venvnflg40q7/requirements.txt
[2025-02-13T06:19:26.831+0000] {process_utils.py:186} INFO - Output:
[2025-02-13T06:19:28.744+0000] {process_utils.py:190} INFO - Collecting pandas (from -r /tmp/venvnflg40q7/requirements.txt (line 1))
[2025-02-13T06:19:28.745+0000] {process_utils.py:190} INFO -   Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/f8/7f/5b047effafbdd34e52c9e2d7e44f729a0655efafb22198c45cf692cdc157/pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
[2025-02-13T06:19:28.747+0000] {process_utils.py:190} INFO -   Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
[2025-02-13T06:19:28.864+0000] {process_utils.py:190} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvnflg40q7/requirements.txt (line 1))
[2025-02-13T06:19:28.865+0000] {process_utils.py:190} INFO -   Obtaining dependency information for python-dateutil>=2.8.2 from https://files.pythonhosted.org/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata
[2025-02-13T06:19:28.867+0000] {process_utils.py:190} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2025-02-13T06:19:28.946+0000] {process_utils.py:190} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvnflg40q7/requirements.txt (line 1))
[2025-02-13T06:19:28.947+0000] {process_utils.py:190} INFO -   Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/eb/38/ac33370d784287baa1c3d538978b5e2ea064d4c1b93ffbd12826c190dd10/pytz-2025.1-py2.py3-none-any.whl.metadata
[2025-02-13T06:19:28.948+0000] {process_utils.py:190} INFO -   Using cached pytz-2025.1-py2.py3-none-any.whl.metadata (22 kB)
[2025-02-13T06:19:28.978+0000] {process_utils.py:190} INFO - Collecting tzdata>=2022.1 (from pandas->-r /tmp/venvnflg40q7/requirements.txt (line 1))
[2025-02-13T06:19:28.979+0000] {process_utils.py:190} INFO -   Obtaining dependency information for tzdata>=2022.1 from https://files.pythonhosted.org/packages/0f/dd/84f10e23edd882c6f968c21c2434fe67bd4a528967067515feca9e611e5e/tzdata-2025.1-py2.py3-none-any.whl.metadata
[2025-02-13T06:19:28.980+0000] {process_utils.py:190} INFO -   Using cached tzdata-2025.1-py2.py3-none-any.whl.metadata (1.4 kB)
[2025-02-13T06:19:29.478+0000] {process_utils.py:190} INFO - Collecting numpy>=1.20.3 (from pandas->-r /tmp/venvnflg40q7/requirements.txt (line 1))
[2025-02-13T06:19:29.479+0000] {process_utils.py:190} INFO -   Obtaining dependency information for numpy>=1.20.3 from https://files.pythonhosted.org/packages/98/5d/5738903efe0ecb73e51eb44feafba32bdba2081263d40c5043568ff60faf/numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
[2025-02-13T06:19:29.480+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2025-02-13T06:19:29.510+0000] {process_utils.py:190} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvnflg40q7/requirements.txt (line 1))
[2025-02-13T06:19:29.510+0000] {process_utils.py:190} INFO -   Obtaining dependency information for six>=1.5 from https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl.metadata
[2025-02-13T06:19:29.512+0000] {process_utils.py:190} INFO -   Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
[2025-02-13T06:19:29.564+0000] {process_utils.py:190} INFO - Using cached pandas-2.0.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
[2025-02-13T06:19:29.643+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2025-02-13T06:19:29.672+0000] {process_utils.py:190} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2025-02-13T06:19:29.674+0000] {process_utils.py:190} INFO - Using cached pytz-2025.1-py2.py3-none-any.whl (507 kB)
[2025-02-13T06:19:29.678+0000] {process_utils.py:190} INFO - Using cached tzdata-2025.1-py2.py3-none-any.whl (346 kB)
[2025-02-13T06:19:29.680+0000] {process_utils.py:190} INFO - Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
[2025-02-13T06:19:30.004+0000] {process_utils.py:190} INFO - Installing collected packages: pytz, tzdata, six, numpy, python-dateutil, pandas
[2025-02-13T06:19:36.761+0000] {process_utils.py:190} INFO - Successfully installed numpy-1.24.4 pandas-2.0.3 python-dateutil-2.9.0.post0 pytz-2025.1 six-1.17.0 tzdata-2025.1
[2025-02-13T06:19:36.858+0000] {process_utils.py:190} INFO - 
[2025-02-13T06:19:36.858+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.2.1 -> 25.0.1
[2025-02-13T06:19:36.858+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2025-02-13T06:19:37.044+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvnflg40q7/bin/python /tmp/venvnflg40q7/script.py /tmp/venvnflg40q7/script.in /tmp/venvnflg40q7/script.out /tmp/venvnflg40q7/string_args.txt /tmp/venvnflg40q7/termination.log
[2025-02-13T06:19:37.055+0000] {process_utils.py:186} INFO - Output:
[2025-02-13T06:19:37.753+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2025-02-13T06:19:37.753+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 171, in _na_arithmetic_op
[2025-02-13T06:19:37.753+0000] {process_utils.py:190} INFO -     result = func(left, right)
[2025-02-13T06:19:37.753+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 239, in evaluate
[2025-02-13T06:19:37.753+0000] {process_utils.py:190} INFO -     return _evaluate(op, op_str, a, b)  # type: ignore[misc]
[2025-02-13T06:19:37.754+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 70, in _evaluate_standard
[2025-02-13T06:19:37.754+0000] {process_utils.py:190} INFO -     return op(a, b)
[2025-02-13T06:19:37.754+0000] {process_utils.py:190} INFO - TypeError: unsupported operand type(s) for /: 'str' and 'int'
[2025-02-13T06:19:37.754+0000] {process_utils.py:190} INFO - 
[2025-02-13T06:19:37.755+0000] {process_utils.py:190} INFO - During handling of the above exception, another exception occurred:
[2025-02-13T06:19:37.755+0000] {process_utils.py:190} INFO - 
[2025-02-13T06:19:37.755+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2025-02-13T06:19:37.755+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/script.py", line 44, in <module>
[2025-02-13T06:19:37.755+0000] {process_utils.py:190} INFO -     res = transform_dataset(*arg_dict["args"], **arg_dict["kwargs"])
[2025-02-13T06:19:37.755+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/script.py", line 36, in transform_dataset
[2025-02-13T06:19:37.755+0000] {process_utils.py:190} INFO -     df["AvgMonthlyUsage"] = df["TotalCharges"] / df["tenure"]
[2025-02-13T06:19:37.755+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/ops/common.py", line 81, in new_method
[2025-02-13T06:19:37.756+0000] {process_utils.py:190} INFO -     return method(self, other)
[2025-02-13T06:19:37.756+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/arraylike.py", line 210, in __truediv__
[2025-02-13T06:19:37.756+0000] {process_utils.py:190} INFO -     return self._arith_method(other, operator.truediv)
[2025-02-13T06:19:37.756+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/series.py", line 6112, in _arith_method
[2025-02-13T06:19:37.756+0000] {process_utils.py:190} INFO -     return base.IndexOpsMixin._arith_method(self, other, op)
[2025-02-13T06:19:37.757+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/base.py", line 1348, in _arith_method
[2025-02-13T06:19:37.757+0000] {process_utils.py:190} INFO -     result = ops.arithmetic_op(lvalues, rvalues, op)
[2025-02-13T06:19:37.757+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 232, in arithmetic_op
[2025-02-13T06:19:37.757+0000] {process_utils.py:190} INFO -     res_values = _na_arithmetic_op(left, right, op)  # type: ignore[arg-type]
[2025-02-13T06:19:37.757+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 178, in _na_arithmetic_op
[2025-02-13T06:19:37.757+0000] {process_utils.py:190} INFO -     result = _masked_arith_op(left, right, op)
[2025-02-13T06:19:37.757+0000] {process_utils.py:190} INFO -   File "/tmp/venvnflg40q7/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 116, in _masked_arith_op
[2025-02-13T06:19:37.758+0000] {process_utils.py:190} INFO -     result[mask] = op(xrav[mask], yrav[mask])
[2025-02-13T06:19:37.758+0000] {process_utils.py:190} INFO - TypeError: unsupported operand type(s) for /: 'str' and 'int'
[2025-02-13T06:19:38.013+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 395, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 609, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path, tmp_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 463, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
unsupported operand type(s) for /: 'str' and 'int'
[2025-02-13T06:19:38.018+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=download_dataset, task_id=transform_dataset, execution_date=20250213T061405, start_date=20250213T061925, end_date=20250213T061938
[2025-02-13T06:19:38.031+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 28 for task transform_dataset (Process returned non-zero exit status 1.
unsupported operand type(s) for /: 'str' and 'int'; 815)
[2025-02-13T06:19:38.072+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-13T06:19:38.089+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
